// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['services']['DocService']['Add'](arg1);
}

export function GetBaseList() {
  return window['go']['services']['DocService']['GetBaseList']();
}

export function GetDocTree() {
  return window['go']['services']['DocService']['GetDocTree']();
}
