// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function Add(arg1:models.Doc):Promise<services.ServiceResponse>;

export function GetBaseList():Promise<Array<models.Doc>>;

export function GetDocTree():Promise<services.ServiceResponse>;
